### ISSUE TITLE
Versioned & minified fields.json

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/stac-fields#12]
PySTAC fetches the schema at `https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields/fields-normalized.json` dynamically when creating Collection summaries. There is a chance that the file could be updated in a way that breaks or changes functionality in PySTAC. The file also contains whitespace that makes it more human-readable but increases the payload size.

Would it be possible to version this schema so that we could pin each PySTAC release to a specific schema and also provide a minified version to reduce the size of the response?

See stac-utils/pystac#400 for context

**Comment by m-mohr** [comment]
Once we've reached 1.0.0 (which will likely still take a month or two), it will be versioned according to semver and you could for example simply request `https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields@1/fields-normalized.json` (see the @1, which sticks to the major version 1.x.x). I don't plan any updates to fields.json anymore in beta/rc/stable 1.x.x - the beta status is really just the code around it that formats in JS.

There's no plan for a minified version right now. I'm actually surprised that this is relevant in Python?!
