### ISSUE TITLE
Add proj:code to support Projection extension v2

### ISSUE THREAD

**Issue by jsignell** [stac-utils/stac-fields#26]
When https://github.com/stac-extensions/projection/pull/12 lands in the projection extension and a 2.0 is released, proj:epsg will be replaced by proj:code. I am not sure how this libaray handles different versions of extensions.

I was working on https://github.com/stac-utils/pystac/pull/1287 and noticed that pystac depends on this library for summary fields, so just wanted to open this.

**Comment by m-mohr** [comment]
Implemented in ebd9c99a
