### ISSUE TITLE
Hint on stats vs collecting all values?

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stac-fields#6]
Would it make sense to add something to stac-fields to hint whether numeric values should not generally be summarized?

See [this comment](https://github.com/stac-utils/pystac/pull/264#issue-577081099): 'For instance, for numeric values, there should be some information about whether to calculate stats or just collect all existing values (as it happens with epsg codes)'

**Comment by m-mohr** [comment]
That seems reasonable, something like:

summary not set: follow general guidelines (numbers = range, others = values)
summary: null (or false? => don't summarize)
summary: "range"
summary: "values"

**Comment by m-mohr** [comment]
Oh and happy to also implement this in the next days for beta.7 so that we can get it into pystac and also get feedback on it.

**Comment by m-mohr** [comment]
I've just started implementing this. What other fields except proj:epsg need a special handling?

**Comment by m-mohr** [comment]
Has been released as 1.0.0-beta.7, but the fields above are still open for clarification until rc.1.

**Comment by volaya** [comment]
For the case of fields to be summarized as an array ("v"), where is the information about whether to merge individual arrays or not? there was a `mergeArrays` property, but that is not used now in the fields.json file. Maybe there should be two different values to indicate that the summarize should be an array? (array just collecting all single values, even if they are arrays themselves, and array created by combining individual ones")

**Comment by m-mohr** [comment]
All arrays have to be merged. So if the data type of the value is array and it is not forbidden to create summaries or set to json schema, you have to merge.

**Comment by m-mohr** [comment]
No additional feedback received, closing until users demand an improvement.
